# Generated by Django 4.2.6 on 2023-10-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjectsPassed',
        ),
        migrations.AddField(
            model_name='student',
            name='paidFees',
            field=models.BooleanField(default=False),
        ),
    ]
