# Generated by Django 4.2.6 on 2023-11-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_email_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
